apiVersion: v1
kind: Service
metadata:
    labels:
        app: myapp
    name: myapp-svc
spec:
    ports:
    - port: 3300
      protocol: TCP
      targetPort: 3300
    selector:
        app: myapp
    type: ClusterIP